### ISSUE TITLE
Error in v1.1.0

### ISSUE THREAD

**Issue by iiz00** [dalcantara7/obsidian-auto-moc#7]
In version 1.1.0, the following error is still observed in my environment.

Add missing linked mentions:
```
undefined
plugin:auto-moc:148 Uncaught TypeError: Cannot read properties of undefined (reading 'aliases')
    at AutoMOC.addMissingLinks (plugin:auto-moc:148:26)
    at AutoMOC.runAutoMOC (plugin:auto-moc:169:12)
    at Object.editorCallback (plugin:auto-moc:186:16)
    at Object.t.mobileOnly.Mb.isMobile.t.checkCallback (app.js:1:1640123)
    at jz (app.js:1:1639584)
    at e.onChooseItem (app.js:1:1685533)
    at e.onChooseSuggestion (app.js:1:1492273)
    at e.selectSuggestion (app.js:1:1491823)
    at t.useSelectedItem (app.js:1:1389248)
    at t.onSuggestionClick (app.js:1:1388986)
```
Add missing notes with specific tag:
undefined
```
plugin:auto-moc:148 Uncaught TypeError: Cannot read properties of undefined (reading 'aliases')
    at AutoMOC.addMissingLinks (plugin:auto-moc:148:26)
    at AutoMOC.runAutoMOC (plugin:auto-moc:169:12)
    at TagSuggestModal.onChooseItem (plugin:auto-moc:101:17)
    at TagSuggestModal.e.onChooseSuggestion (app.js:1:1492273)
    at TagSuggestModal.e.selectSuggestion (app.js:1:1491823)
    at t.useSelectedItem (app.js:1:1389248)
    at t.onSuggestionClick (app.js:1:1388986)
    at HTMLDivElement.s (enhance.js:1:7956)
```
As for alias, I have a template file for alias like this:
```
---
aliases: []
---
```

**Comment by dalcantara7** [comment]
It looks like there was an update to Obsidian released 2 days ago. From what I can see, this update changed the way the api handles file aliases and the way I was checking before no longer worked. I have released update 1.1.1 to handle this new format. Please update the plugin and let me know if you encounter any bugs. If the plugin works as expected, please let me know via this issue and I will close it.

Thanks.

**Comment by iiz00** [comment]
Now it seems to work properly. Thank you!
